global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.100.242:9090']
        labels:
          instance: prometheus
  # - job_name: "cadvisor"
  #   static_configs:
  #   - targets: ['172.16.9.89:9101', '172.16.9.90:9101']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['192.168.100.242:9091']
        labels:
          instance: pushgateway
  - job_name: 'mongo_exporter'
    static_configs:
      - targets: ['192.168.100.242:9216']
        labels:
          instance: mongo
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['172.16.9.89:9100', '172.16.9.90:9100']
  # - job_name: 'zipkin'
  #   scrape_interval: 5s
  #   metrics_path: '/prometheus'
  #   static_configs:
  #     - targets: ['172.16.9.89:9411']
  # - job_name: 'nacos'
  #   scrape_interval: 5s
  #   metrics_path: /nacos/actuator/prometheus
  #   file_sd_configs:
  #   - refresh_interval: 1m
  #     files:
  #     - conf/nacos.json

  ## 业务服务
  # - job_name: 'caesar_server'
  #   scrape_interval: 5s
  #   metrics_path: /tech/metrics
  #   file_sd_configs:
  #   - refresh_interval: 1m
  #     files:
  #     - conf/caesar_server.json