version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      # - /home/quant_group/data/mongo:/data/db
      - D:\docker\data\mongo:/data/db
    ports:
      - 27017:27017
