version: "3"
services:
 mysql:
  image: mysql:5.7
  container_name: mysql
  restart: always
  command:
   --lower_case_table_names=1
   --character-set-server=utf8mb4
   --collation-server=utf8mb4_general_ci
   --explicit_defaults_for_timestamp=true
  environment:
   TZ: Asia/Shanghai
   MYSQL_ROOT_PASSWORD: 123456
  ports:
   - 13306:3306
  volumes:
   - /data/mysql/data:/var/lib/mysql
   - ./conf:/etc/mysql/conf.d
