version: '3.7'
services:
  zk1:
    image: zookeeper
    container_name: zk1
    restart: always
    ports:
      - "2181:2181"
      - "8881:8080"
    volumes:
      - /home/quant_group/data/zookeeper/zk1/data:/data
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk2:
    image: zookeeper
    container_name: zk2
    restart: always
    ports:
      - "2182:2181"
      - "8882:8080"
    volumes:
      - /home/quant_group/data/zookeeper/zk2/data:/data
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk3:
    image: zookeeper
    container_name: zk3
    restart: always
    ports:
      - "2183:2181"
      - "8883:8080"
    volumes:
      - /home/quant_group/data/zookeeper/zk3/data:/data
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182,zk3:2183
      KAFKA_LOG_DIRS: /kafka-logs
    volumes:
      - /home/quant_group/data/kafka/kf1/data:/kafka-logs
    depends_on:
      - zk1
      - zk2
      - zk3
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182,zk3:2183
      KAFKA_LOG_DIRS: /kafka-logs
    volumes:
      - /home/quant_group/data/kafka/kf2/data:/kafka-logs
    depends_on:
      - zk1
      - zk2
      - zk3
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182,zk3:2183
      KAFKA_LOG_DIRS: /kafka-logs
    volumes:
      - /home/quant_group/data/kafka/kf3/data:/kafka-logs
    depends_on:
      - zk1
      - zk2
      - zk3

  kafkamanager:
    image: kafkamanager/kafka-manager
    container_name: kafkamanager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zk1,zk2,zk3
    depends_on:
      - zk1
      - zk2
      - zk3
