version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    restart: always
    container_name: xxl-job-admin
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://172.16.9.89:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=123456'
    ports:
      - 8080:8080
    volumes:
      - /home/quant_group/data/xxl-job/applogs:/data/applogs

  executor:
    image: lyr123456/xxl-job-executor-sample-springboot:2.3.0
    container_name: xxl-job-executor
    links:
      - 'xxl-job-admin'
    depends_on:
      - 'xxl-job-admin'
    environment:
      PARAMS: '--xxl.job.admin.addresses=http://172.16.9.89:8080/xxl-job-admin --xxl.job.executor.ip=172.16.9.89'
    ports:
      - 9999:9999
