services:
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - /data/rabbitmq/data:/var/lib/rabbitmq
      - ./conf:/etc/rabbitmq


# 容器启动成功后，进入容器开启management：rabbitmq-plugins enable rabbitmq_management