services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    network_mode: host  # 使用host网络, 访问OLLAMA
    # ports:
    #   - 8080:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434  # 配置 Ollama 地址
      - ENABLE_OPENAI_API=False  # 禁用 OpenAI 集成，卡死的原因就是这个
      - OFFLINE_MODE=True        # 启用离线模式，不从 HuggingFace 拉取模型数据
      - USE_OLLAMA_DOCKER=False  # 不使用集成 Ollama 容器
      - TZ=Asia/Shanghai         # 时区

volumes:
  open-webui:
    external: true  # 声明使用外部已存在的卷