# Hive 之 docker-compose.yaml
## export HIVE_VERSION=3.1.3
## 其中 /data/hive/warehouse 需要777权限

version: '3.9'
services:
  metastore:
    image: apache/hive:${HIVE_VERSION}
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: mysql
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:mysql://192.168.100.38:13306/metastore_3.1.3
                     -Djavax.jdo.option.ConnectionUserName=root
                     -Djavax.jdo.option.ConnectionPassword=123456'
    ports:
        - '9083:9083'
    volumes:
        - /data/hive/warehouse:/opt/hive/data/warehouse
        - type: bind
          source: ./lib/mysql-connector.jar
          target: /opt/hive/lib/mysql-connector.jar
    networks:
      - hive

  hiveserver2:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083
                    -Dhive.metastore.warehouse.dir=/opt/hive/data/warehouse'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - /data/hive/warehouse:/opt/hive/data/warehouse
    networks:
      - hive

networks:
  hive:
    name: hive