version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:${NACOS_VERSION}
    volumes:
      - /home/quant_group/data/nacos/cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9849:9848"
      - "9850:9849"
    env_file:
      - ./env/nacos-cluster.env
    restart: always

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    volumes:
      - /home/quant_group/data/nacos/cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8851:8848"
      - "9851:9848"
      - "9852:9849"
    env_file:
      - ./env/nacos-cluster.env
    restart: always

  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    volumes:
      - /home/quant_group/data/nacos/cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8853:8848"
      - "9853:9848"
      - "9854:9849"
    env_file:
      - ./env/nacos-cluster.env
